TeamPage.html

- Added Sami Ahmed to Team Page

#104 Added Sami Ahmed to Team Page Based On main

---

TeamPage.html

-Still needs Joe's image
-Joe and Sunil's improvement goals
-joe's biography

106 and 107 add Joe and Sunil to the Team page

---

TeamPage.html

updated their bio based on what Natalie commented on the related tickets. #106 and #107

updated Sunil and Joe bio

---

TeamPage.html

Added Alana's information to the Team Page.

#112 Add Alana to Website

---

TeamPage.html

Corrected the year that Brenda received her Ph.D.

#116 Update Brenda Buck's Bio

---

TeamPage.html

Updated the team page to include Brandon's profile
Issue #120

Updated team page

---

TeamPage.html

Specify that Brandon is working on the DATIM project in his profile
Issue #120

#120 Specify project being worked on in Brandon's profile

---

TeamPage.html

#123 Add Michelle to Website (Based On main)

---

TeamPage.html

Replaced John's old bio with the new one specified in Issue #125

#125 Updated John Bertini's bio on team page

---

TeamPage.html

- #126 Wes Hart
- updated Wes Hart title --- shortened version to make it look nice and uniform w/ other boxes
- removed improvement goals
- #128 - Natalie
- updated title
- updated bio
- added proficient skills
- added improvement goals
- #130 Kevin Luk
- updated bio
- #132 Ron Wanek
- removed improvement goals

Updated Titles & Bios on Team Page

---

TeamPage.html

Updated Kelvyn's bio on the team page. Also updated his proficient skills section and improvement goals section. Issue #129

#129 Updated Kelvyn's bio, goals, and skils

---

TeamPage.html

Updated Pankeys profile's bio with updated version from Issue #127

#127 Updated Pankey's profile bio

---

ProjectsPage.html
TeamPage.html
index.html

Fixed the footer on 3 pages (home, projects, team) by replacing link with corrected one.
Issue #133

#133 Fixed broken links on site's footer

---

TeamPage.html

Updated Jane's bio and removed improvement goals section
Tasks from Issue #131

#131 Update Jane's Profile on TeamPage

---

TeamPage.html

- #128 Natalie 
- updated bio for new project
- #132 Ron 
- updated profile pic 
- updated bio

Updated Bios & Profile Pics on Team Page

---

ProjectsPage.html
TeamPage.html
index.html

Removed the Phone and Fax numbers.

#141 Update Contact Info

---

TeamPage.html

Sunil's bio has been updated to the newest version from #150

#150 - Updated Sunil's Bio

---

TeamPage.html

Jame's Profile has been updated to the newest version specified in #148.

#148 - Updated Jame's Profile on page

---

TeamPage.html

Daves bio has been updated on the TeamPage as specified in #146

#146 - Updated Daves Bio

---

TeamPage.html

- #145 
- bio sounds better
- #144 
- added new project

#144 #145 Update Bios for Natalie and John - Based on Release 18.0

---

TeamPage.html

#147 - Remove Kevin Luk's Profile - Based on main

---

TeamPage.html

Updated profile to correctly reflect post-graduation information. 
- Replaced Student Programmer with Software Engineer
- Added graduation date
- Added new skills
- Added new goals

Update Alex's Profile

---

TeamPage.html

Addresses #168. Vicki has been added to Team Page for website. I had to adjust font size of job position so that it wouldn't occupy two lines.
---

#168 - Added Vicki to team page

---

TeamPage.html

This change adds the requested changes to Gretchen's Profile as detailed in #171 
---

#171 - Update Gretchen's Profile

---

TeamPage.html

Hello, this PR updates John's title on the team page.
---

#174 - Updated John Bertini's Title

---

ProjectsPage.html

This PR adds the new projects as requested in Issue #181 
Note:
- Natalie and I both agreed that an acronym (SNBE) used in the description for a project should be removed. Therefore, there is a slight difference between my project description and the issue's project description.
- Made text alignment styling changes to some other project acronyms to get rid of gaps in text.

#181 Add New Projects

---

ProjectsPage.html

The acronym 508 has been updated to Section 508 in the projects page.

#184 - Update 508

---

ProjectsPage.html

Updated UMaestro on projects page as described in #183 .

#183 - Updated UMaestro

---

TeamPage.html

Addresses #187. Alana got hired full time! 
<h2>CODE CHANGES</h2>
- updated job title
- updated job description
- fixed a lil wording problem

#187 Update Alana's Profile - Based on main

---

TeamPage.html

Addresses #190. Removed Angie from Team Page. :((

Removed Angie's Profile - Based on main

---

TeamPage.html

Addresses #193. Updated Bio to say EVALIDator project too.

#193 - Update Alex's Bio

---

ProjectsPage.html

Addresses #196. Projects list needed to be alphabetized by acronym.

#196 - Alphabetized Projects List - Based on main

---

ProjectsPage.html

Addresses #195. Added FIA Spatial Database to Projects Page.

#195 Add FIA Spatial Database to Projects Page - Based on main 

---

ProjectsPage.html

Addresses #199. Added NVCS to Projects Page while maintaining alphabetical order.

#199 Add NVCS to Projects Page - Based on main

---

TeamPage.html

Addresses #203. 
- updated profile pic
- updated bio

#203 Update Brenda's Profile - Based on main 

---

ProjectsPage.html

Addresses issue #205. Two tables needed to be created to separate current and no more working on UNLV-FIA projects. 
<h2>CODE CHANGES</h2>
- created two new tables: current & previous 
- list of current projects: 
***ETL is in the current projects
- updated ETL project description
- formatted document

#205 Current & Previous Projects Tables - Based on main 

---

TeamPage.html

This pull request is for issue #209 
1. Added CJ Ballesteros' Profile
- Note that Charles Joseph Ballesteros was too long for the box and would mess up formatting, so it was shortened to CJ Ballesteros.
- Added Picture, as well as making sure the button leading to the profile works.
- Added Name, Job Title, Work Location, Email, Biography, Proficient Skills, and Improvement Goals

#209 (UNLV-FIA Homepage) Add Charles Ballesteros Profile to Team Page. (Based On main)

---

TeamPage.html

This pull request is for issue #207 
1. Added Chris Rosado profile to team page

#207 (UNLV-FIA-Homepage) Add profile on website for Chris (Based on main)

---

TeamPage.html

This pull request is for issue #208 
- Added profile to team page.
- Updated all relevant information.

#208 (UNLV-FIA Homepage) Add Zach Dorff Profile to Team Page. (Based On main)

---

TeamPage.html

This is for issue #210 
- added Stacey alphabetically
- ensured image size, ids, and no disruption to existing employees

#210 (UNLV-FIA Homepage) Add Stacey Lai Profile to Team Page. (Based On main)

---

ProjectsPage.html

Addition to #205. 
Added: 
- National Science Strategy to the Current Projects List
- added FIA Datamart as a new current project

#205 Additional Current Projects - Based on main

---

TeamPage.html

Addresses #218
- updated title: Senior Enterprise Database Architect
- shortened Senior to Sr. because it wouldn't fit and make everything uniform
- updated bio

#218 - Update Joe Tschida's Profile - Based on main

---

TeamPage.html

This is for issue #220 
---
- Small update to the biography section for Sunil Manzor

#220- Update Sunil Manzors Bio - BasedOn - Main

---

TeamPage.html

Addresses #222 
- updated bio to include EVALIDator and UMaestro projects

#222 - Updated Michelle's Bio - Based on main

---

TeamPage.html

Addresses #227.
- title updated to Senior Software Engineer

#227 Update Kelvyn's Title

---

TeamPage.html
index.html

Updates the bios according to #229, #230, #231.
1. Updates the profiles of Sunil, Kelvyn, Dave, and CJ.
1. Team Page

#229/#230/#231 (Team Page) Update Bios | Based on Main

---

TeamPage.html

Addresses #233.
Start date now only says early 2024.

#233 Update Joe's Bio - Based on main

---

TeamPage.html

Addresses #233 
- removed early, now only says in 2024

#233 - Update Joe's Bio - Based on main

---

TeamPage.html

This is for issue #239 
---
Updated my own bio and skills in the team page section.

Updated bio,skills and title.

---

TeamPage.html

Addresses #240. 
- bio now has graduated date
- improvement goals
- title update

#240 - Update Michelle's Profile

---

TeamPage.html

This is for #246 
Added Joh's entire profile to teams page.

#246 Add Joh Parker Profile to Website

---

TeamPage.html

Addresses issue #241 
1. Added Jessica Nguyen's profiles to UNLV-FIA Teams Page

#241 Add Jessica Nguyen Profile to Website (UNLV-FIA Teams Page) Based On Main

---

TeamPage.html

This is for #245 
- Added Hannah's profile to the teams page.

#245 Add Hannah Faye Yap Profile to Website

---

TeamPage.html

Addresses issue #244 
1. Added Luiza's profile to UNLV-FIA Team Page

#244 Add Luiza Novytska Profile to Website (UNLV-FIA Teams Page) Based On Main 

---

TeamPage.html

This is for #245 
- Removed Biography: Hannah's profile on team page.

Removed "Biography:"

---

TeamPage.html

Addresses issues #247, #257, #261, #263, #265 
1. Updated Descriptions of each of the members listed in the title above.
1. Check each description matches Issue's provided description.
2. Ensure no grammatical errors appear.

#247/257/261/263/265 (Team Page) Update Alana, Brenda, CJ, John, & Brian descriptions | Based On: Main

---

TeamPage.html

Addresses #256, #258. Please check to see if I missed any grammar or spelling issues!
1. Updated content of Meet Our Team section and Gretchen's profile

#256/#258 (Team Page) Meet Our Team/Gretchen Andrew Profile | Based on Main

---

TeamPage.html

Addresses #260, #262, #264, #267, #269, #271, #273. Please check to see if I missed any grammar or spelling issues!
1. Updated content of Sami Ahmed, Helen Beresford, Dave Castillo, Zach Dorff, Alex Fox, Kelvyn Meyers, and Luiza Novytska's profiles.

#260/#262/#264/#267/#269/#271/#273 (Team Page) Update numerous profiles | Based on Main

---

TeamPage.html

Addresses issue #268, #270, #272, #274 
1. Updated Profiles of the people matching the issues above

#268/#270/#272/#274 Update Multiple Profile descriptions BasedOn Master Release Master

---

TeamPage.html

Addresses issue #288 
1. Updated Profile for myself (it hasn't been changed since I started it got a little too dusty)

Updated Profile for Chris Rosado

---

ProjectsPage.html
TeamPage.html
index.html

Addresses issues #296, #297, #298, #299, #301, #302 on UNLV-FIA website
1. Altered text on TeamPage, ProjectsPage, & homePage
1. Go to each of the Pages list above 
2. For each page view tickets related to those pages
3. See modifications to text on each page

#296-#302 Modifications to UNLV-FIA Website BasedOn Main Release Main

---

index.html

Addresses issues on #304 
1. Removed the word "diversity"

#304 Modification to About UNLV-FIA BasedOn Main Release Main

---

TeamPage.html

Addresses issue #306 
1. Update Luzia's profile per issue #306's requirements

#306 Update Employee profile Luiza Novytska BasedOn Main Release Main
